#!/bin/bash

diff <(grep 'flags' /proc/cpuinfo | head -n1 | sed 's/^.*: \(.*\)/\1/' | tr ' ' '\n' | sort) <(sort << Core_ix
aes
avx
cx16
fsgsbase
fxsr
mmx
pclmulqdq
popcnt
lahf_lm
sse
pni
sse2
sse4_1
sse4_2
ssse3
xsave
xsaveopt
Core_ix
) | grep '^>' >/dev/null

if [ $? -eq 1 ]; then
	arch="coreix"
else
	arch="presc2m"
fi

options=()
debug=0
mode="rel"
for option in "$@"; do
	if [ "$option" == "--debug" ]; then
		debug=1
		mode="dbg"
	else
		options+=("$option")
	fi
done

current_dir=$(dirname "`readlink -f "${BASH_SOURCE[0]}"`")
binary="$current_dir"/__anja_"$mode"_"$arch"/anja

if [ $debug -eq 1 ]; then
	gdb --args "$binary" "${options[@]}"
else
	exec "$binary" "${options[@]}"
fi
