#!/bin/bash

diff <(grep 'flags' /proc/cpuinfo | head -n1 | sed 's/^.*: \(.*\)/\1/' | tr ' ' '\n' | sort) <(sort << Core_ix
aes
avx
cx16
fsgsbase
fxsr
mmx
pclmulqdq
popcnt
lahf_lm
sse
pni
sse2
sse4_1
sse4_2
ssse3
xsave
xsaveopt
Core_ix
) | grep '^>'
