#!/bin/bash

diff <(grep 'flags' /proc/cpuinfo | head -n1 | sed 's/^.*: \(.*\)/\1/' | tr ' ' '\n' | sort) <(sort << Core_ix
aes
avx
cx16
fsgsbase
fxsr
mmx
pclmulqdq
popcnt
lahf_lm
sse
pni
sse2
sse4_1
sse4_2
ssse3
xsave
xsaveopt
Core_ix
) | grep '^>' >/dev/null

current_dir=$(dirname "`readlink -f "${BASH_SOURCE[0]}"`")

if [ $? -eq 1 ]; then
	exec "$current_dir"/__anja_rel_coreix/anja "$@"
fi
exec "$current_dir"/__anja_rel_presc2m/anja "$@"
